### ISSUE TITLE
Two Cookies with the same Name

### ISSUE THREAD

**Issue by ekanna** [goji/csrf#10]
Hi @elithrar ,

Browser is sending two cookies with the same name "goji_csrf"? How is that possible?
If i remove one cookie and make a request via curl . It is working fine.

And i can't see the goji_csrf cookies in "Developer Tools" --> "Application" --> "Cookies".
Where are they exactly getting saved in browser?

I can see them only in Request Headers. Below is the sample cookie, taken from Request Headers.

Cookie:_goji_csrf=MTQ3NTE1MjkzM3xJa2RrY0hCeU4xQkZSVEZWVUc4d1VVeG1RMWxtVkRKemFrMTRiMEpzVDNCbFdUWjNhVWN2YkVKT2JFRTlJZ289fGYBhIh1BbSLuowH9_9kE8OMMhERHRDX3sUvnJ5lVMe5; _goji_csrf=MTQ3NTE1MjkzNHxJbWRTUTNKc1oxTjNiMGhDTVdJd1RTOVlWbVpaYldWUmJWbE5aUzlGVVU5RU0zQmFPR0pqTW0xWU0yODlJZ289fCIQUKoyL7WIwS5gvwEA6O3ZPo284a2CUrXjems0ifcm;

Thanks

**Comment by elithrar** [comment]
What browser and can you share the full cookie details? (expiries, domain,
HttpOnly?)

**Comment by ekanna** [comment]
Hi @elithrar 
Thanks for prompt response,
Here is the screen shot. I am using Chrome browser (Version 53.0.2785.116 (64-bit)) on MacbookPro

![image](https://cloud.githubusercontent.com/assets/248011/18965426/d8447dd4-869a-11e6-9901-6b4d8324a38e.png)

**Comment by ekanna** [comment]
I am using httpOnly.

Why i am not able to see _goji_csrf  cookies in doverloper tools, at below location?
Where exactly are they stored in browser?

![image](https://cloud.githubusercontent.com/assets/248011/18965746/0c11fe9c-869c-11e6-9dba-e0598e27bec8.png)

Thanks

**Comment by elithrar** [comment]
That's exactly where they are stored. Do you have any browser addons or otherwise that might be interfering here? If you clear your cookies, does it continue to occur?

**Comment by ekanna** [comment]
If i clear my cookies and start again, it is working fine for some time. I have "vue js dev tool" add-on and nothing else. I have installed "EditThisCookie" add-on to find out where cookies are stored. But i could not find them.

Thanks

**Comment by elithrar** [comment]
Cookies are stored in the browser's internal cache. The web inspector and EditThisCookie will show you all the cookies it has stored. There's no other place to look.

**Comment by elithrar** [comment]
(closing this as it's not clear it's an issue with goji/csrf)
