### ISSUE TITLE
Supporting Goji v2 (goji.io)

### ISSUE THREAD

**Issue by elithrar** [goji/csrf#5]
With Goji v2 (https://github.com/goji/goji) close to reaching stability, there will be a need to make a change to support Goji's `goji.Handler` interface and use `net/context` instead of/in addition to `web.C`.

The two approaches I'm considering:
- Add a `ProtectC(authKey []byte, opts ...Option) func(goji.Handler) goji.Handler` function, and add a `ServeHTTPC` method to the `*csrf` type. Calling `ProtectC` would set a `useContext` field in `*csrf` to true, and we would write helpers for getting/setting from appropriate request context (`context.Context` vs. `web.C`) based on that field.
  - _Upsides_: minimal breaking API change for existing users.
  - _Downsides_: internal code more complex, API not as clear to newcomers, `csrf.ErrorHandler` is currently tied to the old `web.Handler` (more API overhead).
- Create a new package that only supports Goji v2.
  - _Upsides_: maintains the small API, provides a similar migration path.
  - _Downsides_: Another package to maintain and port bug fixes/API changes to/from, naming conflict.

@zenazn - open to suggestions here as you may have done some thinking on this already.

**Comment by zenazn** [comment]
Another reason to use a completely different package is to remove a weird "Goji 2 => CSRF => Goji 1" dependency.

**Comment by elithrar** [comment]
Good call. I've created a ["goji-v2" branch](https://github.com/elithrar/csrf/tree/goji-v2) with a new API and updated tests. This was an easy change since the package is fairly simple—most of the work was changing the request context throughout.

Breaking changes:
- `csrf.Protect` now returns `func(goji.Handler) goji.Handler` instead of `web.Handler`s
- `csrf.ErrorHandler` now accepts a `goji.Handler` instead of a `web.Handler`
- `context.Context` is used throughout instead of `web.C.Env` (package users need to pass the parent `context.Context` to retrieve the token)

How did you want to manage the naming/living alongside the existing package in the _goji_ organization? Anything but _csrf_ is going to a little awkward, assuming we're still under github.com/goji/*. I'm terrible at naming stuff so open to suggestions here.

**Comment by elithrar** [comment]
Here's a preview of the Goji v2 supporting branch: https://github.com/goji/csrf/tree/csrf-v2-net-context

The only major changes that most users will need to make is to replace the following:
- In your updated, `context.Context` aware handlers:

``` diff
// Where c represents web.C from Goji v1
- token := Token(c, r)
// ctx represents context.Context in Goji v2
+ token := Token(ctx, r)
```
- Also update how the middleware is applied - `UseC` instead of `Use`:

``` diff
- mux.Use(csrf.Protect([]byte(key)))
+ mux.UseC(csrf.Protect([]byte(key)))
```

I still need to decide how to have this co-exist alongside the existing `goji/csrf` package. I think I'm ultimately forced into putting it under a new name or forcing something like [gopkg.in](http://labix.org/gopkg.in) to version the import path.

**Comment by elithrar** [comment]
@zenazn Are you interested in donating a `goji.io` vanity URL for the v2 csrf package—alongside still hosting the new repo in the Goji GitHub org?
- Since the `go-imports` meta tag can't be used to point to a rev/branch (yet!) you would need to create a `ctx-csrf` repo that I can push the v2 branch to; and
- Setup a vanity URL -e.g.`goji.io/pkg/csrf` or `goji.io/community/v1/csrf` (or whatever you feel is suitable!)

Else I'll host this on my GitHub profile as `elithrar/goji-csrf` and update the Wiki!

**Comment by zenazn** [comment]
I wasn't planning on hosting more vanity names under `goji.io`—the process is (unfortunately) pretty manual right now, and I think it makes more sense for package authors to have more control over the process instead of needing to round-trip through me any time they want to make a subpackage.

I'm still more than happy to make new repositories under `github.com/goji` though—just let me know what name you want! (`ctx-csrf` works for me if that's what you want)

**Comment by elithrar** [comment]
I can understand that. I'm using GitHub Pages + jekyll + YAML front-matter to handle vanity URLs for a new project and it's definitely _very_ manual!

`ctx-csrf` with the description "ctx-csrf is Cross Site Request Forgery (CSRF) prevention middleware for Goji (https://goji.io) and Go services that support net/context (https://golang.org/x/net/context)"

I'll push the branch up once the repo exists/I have permissions. Thanks in advance and enjoy the holiday period!

**Comment by zenazn** [comment]
boop! https://github.com/goji/ctx-csrf

Happy holidays to you too!

**Comment by elithrar** [comment]
Pushed. Flick the Travis CI switch when you have the chance—thanks again Carl.

**Comment by zenazn** [comment]
done!

**Comment by elithrar** [comment]
https://github.com/gorilla/csrf supports the latest Goji out of the box, as everything has rallied around `request.Context()`.
